export default [
  { number: 0, spanish: "cero" },
  { number: 1, spanish: "uno" },
  { number: 2, spanish: "dos" },
  { number: 3, spanish: "tres" },
  { number: 4, spanish: "cuatro" },
  { number: 5, spanish: "cinco" },
  { number: 6, spanish: "seis" },
  { number: 7, spanish: "siete" },
  { number: 8, spanish: "ocho" },
  { number: 9, spanish: "nueve" },
  { number: 10, spanish: "diez" },
  { number: 11, spanish: "once" },
  { number: 12, spanish: "doce" },
  { number: 13, spanish: "trece" },
  { number: 14, spanish: "catorce" },
  { number: 15, spanish: "quince" },
  { number: 16, spanish: "dieciséis" },
  { number: 17, spanish: "diecisiete" },
  { number: 18, spanish: "dieciocho" },
  { number: 19, spanish: "diecinueve" },
  { number: 20, spanish: "veinte" },
  { number: 21, spanish: "veintiuno" },
  { number: 22, spanish: "veintidós" },
  { number: 23, spanish: "veintitrés" },
  { number: 24, spanish: "veinticuatro" },
  { number: 25, spanish: "veinticinco" },
  { number: 26, spanish: "veintiséis" },
  { number: 27, spanish: "veintisiete" },
  { number: 28, spanish: "veintiocho" },
  { number: 29, spanish: "veintinueve" },
  { number: 30, spanish: "treinta" },
  { number: 31, spanish: "treinta y uno" },
  { number: 32, spanish: "treinta y dos" },
  { number: 33, spanish: "treinta y tres" },
  { number: 34, spanish: "treinta y cuatro" },
  { number: 35, spanish: "treinta y cinco" },
  { number: 36, spanish: "treinta y seis" },
  { number: 37, spanish: "treinta y siete" },
  { number: 38, spanish: "treinta y ocho" },
  { number: 39, spanish: "treinta y nueve" },
  { number: 40, spanish: "cuarenta" },
  { number: 41, spanish: "cuarenta y uno" },
  { number: 42, spanish: "cuarenta y dos" },
  { number: 43, spanish: "cuarenta y tres" },
  { number: 44, spanish: "cuarenta y cuatro" },
  { number: 45, spanish: "cuarenta y cinco" },
  { number: 46, spanish: "cuarenta y seis" },
  { number: 47, spanish: "cuarenta y siete" },
  { number: 48, spanish: "cuarenta y ocho" },
  { number: 49, spanish: "cuarenta y nueve" },
  { number: 50, spanish: "cincuenta" },
  { number: 51, spanish: "cincuenta y uno" },
  { number: 52, spanish: "cincuenta y dos" },
  { number: 53, spanish: "cincuenta y tres" },
  { number: 54, spanish: "cincuenta y cuatro" },
  { number: 55, spanish: "cincuenta y cinco" },
  { number: 56, spanish: "cincuenta y seis" },
  { number: 57, spanish: "cincuenta y siete" },
  { number: 58, spanish: "cincuenta y ocho" },
  { number: 59, spanish: "cincuenta y nueve" },
  { number: 60, spanish: "sesenta" },
  { number: 61, spanish: "sesenta y uno" },
  { number: 62, spanish: "sesenta y dos" },
  { number: 63, spanish: "sesenta y tres" },
  { number: 64, spanish: "sesenta y cuatro" },
  { number: 65, spanish: "sesenta y cinco" },
  { number: 66, spanish: "sesenta y seis" },
  { number: 67, spanish: "sesenta y siete" },
  { number: 68, spanish: "sesenta y ocho" },
  { number: 69, spanish: "sesenta y nueve" },
  { number: 70, spanish: "setenta" },
  { number: 71, spanish: "setenta y uno" },
  { number: 72, spanish: "setenta y dos" },
  { number: 73, spanish: "setenta y tres" },
  { number: 74, spanish: "setenta y cuatro" },
  { number: 75, spanish: "setenta y cinco" },
  { number: 76, spanish: "setenta y seis" },
  { number: 77, spanish: "setenta y siete" },
  { number: 78, spanish: "setenta y ocho" },
  { number: 79, spanish: "setenta y nueve" },
  { number: 80, spanish: "ochenta" },
  { number: 81, spanish: "ochenta y uno" },
  { number: 82, spanish: "ochenta y dos" },
  { number: 83, spanish: "ochenta y tres" },
  { number: 84, spanish: "ochenta y cuatro" },
  { number: 85, spanish: "ochenta y cinco" },
  { number: 86, spanish: "ochenta y seis" },
  { number: 87, spanish: "ochenta y siete" },
  { number: 88, spanish: "ochenta y ocho" },
  { number: 89, spanish: "ochenta y nueve" },
  { number: 90, spanish: "noventa" },
  { number: 91, spanish: "noventa y uno" },
  { number: 92, spanish: "noventa y dos" },
  { number: 93, spanish: "noventa y tres" },
  { number: 94, spanish: "noventa y cuatro" },
  { number: 95, spanish: "noventa y cinco" },
  { number: 96, spanish: "noventa y seis" },
  { number: 97, spanish: "noventa y siete" },
  { number: 98, spanish: "noventa y ocho" },
  { number: 99, spanish: "noventa y nueve" },
];
